# Generated by Django 4.2.13 on 2024-05-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_team_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_featured',
        ),
    ]
