# Generated by Django 4.2.13 on 2024-05-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_car_cars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cars',
            new_name='car',
        ),
    ]
