# Generated by Django 4.2.13 on 2024-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_minage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='minage',
            field=models.IntegerField(max_length=150),
        ),
    ]
