# Generated by Django 4.2.13 on 2024-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='minage',
            field=models.IntegerField(),
        ),
    ]
