# Generated by Django 4.2.13 on 2024-06-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_car_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transission',
            field=models.CharField(choices=[('Aut0matic', 'Automatic'), ('Manual', 'Manual')], max_length=150),
        ),
    ]
