# Generated by Django 4.2.13 on 2024-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_car_transission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=150),
        ),
    ]
